FROM ubuntu:latest

RUN 						\
	apt-get update 			\
	&& apt-get upgrade -y 	\
	&& apt-get install -y git-core curl nano libssl-dev python3-dev python3-pip iproute2

RUN git clone https://github.com/http3-prioritization/aioquic.git /srv/aioquic \
    && cd /srv/aioquic \
    && git fetch \
    && git checkout early-data-testing
  
# https://stackoverflow.com/a/78652149
# I HATE PYTHON SO MUCH

SHELL ["/bin/bash", "-c"] # default is sh, which doesn't mash well with python

RUN cd /srv/aioquic \
 && apt install -y python3-venv \
 && python3 -m venv .venv \
 && source .venv/bin/activate \
 && pip install -e . \
 && pip install asgiref dnslib "flask<2.2" httpbin starlette "werkzeug<2.1" wsproto aiofiles setuptools \
 && mkdir /srv/aioquic/qlog/

ENTRYPOINT ["bash"]